# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  version: '0.1.0'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: $(System.DefaultWorkingDirectory)\*.sln
    clean: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.sln'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/IntelliTectAnalyzer.csproj'
    versioningScheme: 'off'
    arguments: '-p:PackageVersion=$(version) --version-suffix $(Build.BuildId)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'